### ISSUE TITLE
A question of differences between general and precision general

### ISSUE THREAD

**Issue by expnkx** [jk-jeon/Grisu-Exact#6]
![image](https://user-images.githubusercontent.com/57303909/75136165-c276ff00-56b1-11ea-8fc3-05ee1941202e.png)
Can I just add zero to general to gain precision general? It looks like ryu algorithm provides more inaccurate results with fixed mode compared to just add zero after general. Why?

Is there any rule for precision floating point rounding?

**Comment by jk-jeon** [comment]
What's your idea about how 0.0001 is stored inside memory?

If you expand 0.0001 in base 2, it becomes

0x1.a36e2eb1c432ca... * 2^-66

There is no way to store the "exact" value as a binary number, because the denominator of your number (0.0001) has a prime factor not equal to 2. This means the expansion must be infinite, just like you can't express 1/3 as a decimal number with finitely many digits.

Most of the machines today use binary representations for floating-point number because it is way faster and simpler than decimal representations. The price to pay is inability to store the exact value of relatively simple numbers like 0.0001.

The precision (number of binary digits) used by IEEE-754 binary64 format (aka `double`) is 53. That means, you need to round up the 54th digit of 0x1.a36e2eb1c432ca..., thus the final number you end up storing is actually

0x1.a36e2eb1c432d * 2^-14 = 0.000100000000000000004792173602385929598312941379845142364501953125

So, the inaccuracy is not coming from the output side. It is coming from the input side. For the output side, in fact 0.000100000000000000004792173602385929598312941379845142364501953125 is the "exact" number, and 0.0001 isn't.

To be honest, I don't think this is not an appropriate place to do q/a like this. This has nothing to do with Grisu-Exact. Also, I can't believe someone who doesn't know this kind of thing can actually implement Ryu. Pretty amazing.

**Comment by expnkx** [comment]
> What's your idea about how 0.0001 is stored inside memory?
> 
> If you expand 0.0001 in base 2, it becomes
> 
> 0x1.a36e2eb1c432ca... * 2^-66
> 
> There is no way to store the "exact" value as a binary number, because the denominator of your number (0.0001) has a prime factor not equal to 2. This means the expansion must be infinite, just like you can't express 1/3 as a decimal number with finitely many digits.
> 
> Most of the machines today use binary representations for floating-point number because it is way faster and simpler than decimal representations. The price to pay is inability to store the exact value of relatively simple numbers like 0.0001.
> 
> The precision (number of binary digits) used by IEEE-754 binary64 format (aka `double`) is 53. That means, you need to round up the 54th digit of 0x1.a36e2eb1c432ca..., thus the final number you end up storing is actually
> 
> 0x1.a36e2eb1c432d * 2^-14 = 0.000100000000000000004792173602385929598312941379845142364501953125
> 
> So, the inaccuracy is not coming from the output side. It is coming from the input side. For the output side, in fact 0.000100000000000000004792173602385929598312941379845142364501953125 is the "exact" number, and 0.0001 isn't.
> 
> To be honest, I don't think this is not an appropriate place to do q/a like this. This has nothing to do with Grisu-Exact. Also, I can't believe someone who doesn't know this kind of thing can actually implement Ryu. Pretty amazing.

Ha. I am going to provide a general interface and separate the floating-point logic to 3 ends just like a compiler. The user can switch any of them

1. front-end:
floating point bit_cast to integer. Maximum length determines, Special case, Nan, Inf format (like uppercase), space assignment, sign.
2. middle-end
This takes only one pointer. It can switch between multiple algorithms. ryu, grisu-exact or whatever. User can use their own algorithm to replace this part. (There is no point for algorithm authors to do front-end and back-end repeatedly)
3. back-end
The actual deal with the output device. switch between scientific or fixed
Use fast integer output algorithms
